### ISSUE TITLE
local host and google cloud app do not work

### ISSUE THREAD

**Issue by reidyoder** [schemaorg/schemaorg#1412]
I'm having issues running my own copy of schema on my own computer. I am following the steps in this article: http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/

When I try to set up my localhost, I get this information: http://pastebin.com/raw/3N2hKc9g. Note that the lines starting at time 01:28:03 print when I try to go to localhost:8080 in my browser.

When I try to interact with the google app engine, I tells me it doesn't recognize the appcfg.py command.

Any help is appreciated.

**Comment by RichardWallis** [comment]
Related to issue (#1384)

**Comment by RichardWallis** [comment]
Fixed by commit df0d380947fadf62dcfe29436c1c7c69844107c3

**Comment by reidyoder** [comment]
Thanks! That fixed my localhost issue. I'm still getting "bash: appcfg.py: command not found" after typing "appcfg.py update schemaorg/" though. Do you know why this could be?

**Comment by Dataliberate** [comment]
Not sure exactly why, as setting what I believe to be the correct PATH etc.
does not fix the issue.

However, I find providing the full command path does work:

“C:\Program Files (x86)\Google\Cloud
SDK\google-cloud-sdk\platform\google_appengine\appcfg.py" update schemaorg


~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by reidyoder** [comment]
That fixed it. Thanks again
