### ISSUE TITLE
All offer-specific properties are missing on schema.org/Offer html page

### ISSUE THREAD

**Issue by weirdan** [schemaorg/schemaorg#1718]
![screenshot-schema org-2017-08-15-14-54-27](https://user-images.githubusercontent.com/57403/29315080-e4d3ff40-81c9-11e7-9335-5b91d7ce2adc.png)

Property pages (like http://schema.org/areaServed) list `Offer` as its' possible containing class, but they are nowhere to be found on the Offer page (http://schema.org/Offer, see screenshot above). 

http://schema.org/Offer.rdf is fine though.

**Comment by RichardWallis** [comment]
@weirdan Thanks for highlighting - should be fixed now - a symptom of some issues around a new ship

**Comment by paulwilton** [comment]
all properties are still missing from the webpage
http://schema.org/Offer
can this be reopened ?

**Comment by RichardWallis** [comment]
@paulwilton  Thanks for highlighting [Again!] The issues that this is an occasional symptom of have yet to be fixed - working on it.

~Richard
