### ISSUE TITLE
SMV reports third party context as invalid instead of ignoring it.

### ISSUE THREAD

**Issue by ausi** [schemaorg/schemaorg#2921]
Validating a page with the [Schema Markup Validator](https://validator.schema.org/) that includes schema.org and also other JSON-LD data results in error messages like `There was an invalid type in your JSON-LD.`.

This can be reproduced by entering the following code into the validator:

```
<script type="application/ld+json">
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@type": "Person",
  "name": "Foo"
}
</script>
```

This results in an “Uncategorized Errors” box with the error “There was an invalid type in your JSON-LD.”

<img width="1127" alt="smv-screenshot" src="https://user-images.githubusercontent.com/367169/125291688-f6dc7100-e321-11eb-8e97-0333d7d9a134.png">

This can be very confusing because it is not an “invalid type” but instead a `@context` not supported by the validator.

It would be very helpful if this error could be changed to a notice, something like “Unsupported third party Contexts: The context `https://json-ld.org/contexts/person.jsonld` does not get validated by this validator.”

Is the source code of the validator on GitHub? If so, I can try to make a pull request for this change.

Related question on Stack Overflow: https://stackoverflow.com/questions/68308709

**Comment by danbri** [comment]
Thanks - noted and acknowledged. The tool is not opensource (it is a view provided by Google's structured data validation infrastructure). I will make sure these issues are addressed or documented before we link the new validator more prominently from Schema.org.

**Comment by ausi** [comment]
Thank you very much @danbri !

Can or should I keep this issue open until the validator got fixed?

**Comment by fritzmg** [comment]
@danbri The validator is still showing this as an error. Is the update to the validator still in the pipeline?

**Comment by mlaubacher** [comment]
@danbri Same here still got errors. Is this planned anytime soon?

**Comment by danbri** [comment]
I believe this wouldn't be a trivial change, but I commit to at least documenting what the behaviour is in our next Schema.org release.

**Comment by rrlevering** [comment]
I feel like that's worth a little bit more than a notice, personally.  Especially since we don't stop you from seeing the extracted outputs anyway.  But the context can affect a lot of the interpretation of the markup.  And the concern is that if it wasn't noticed, you could make assumptions that certain schema.org fields were valid on certain types that would be untrue.  If you put "@context": "mycontext.jsonld" in there, suddenly all your validation errors go away because of the change we made last year to only validate known prefixed types and predicates.

However, the message could use some work; it was just lumped in with a more general error.  The new one was just getting some translation work done but should be released shortly.

**Comment by mlaubacher** [comment]
> I feel like that's worth a little bit more than a notice, personally.
+1

otherwise we're on a tough spot. since we handle it correctly but still got a nasty error shown in google search console without knowing for sure if this has any consequences and definitively have a lot to explain to our users.

**Comment by ausi** [comment]
So the error message currently goes like this:

> This @​context string is unknown to the parser and we do not support remote JSON-LD context fetching. Please use a known @​context value (e.g. 'https​://schema.org/') or define a Local Context.

How about extending this a little bit like: 
“Or use a different validator if you need to validate the @​context 'https://mycontext.example.com/'.”

**Comment by ausi** [comment]
![Image](https://github.com/user-attachments/assets/40ff8d24-296c-4774-96ad-a6d5a705984d)

The message still shows up as an error (instead of a notice) and it is impossible to follow the suggestion in many valid use cases. This is very confusing for „regular“ people that try to check their website for errors.
If the message would include a part that acknowledges that a non-schema.org-@​context can be valid the risk of confusion would be greatly reduced.

> If you put "@​context": "mycontext.jsonld" in there, suddenly all your validation errors go away

For that the message could include something like `Make sure that the @​context "https://mycontext.jsonld/" is used on purpose and validate the schema using an appropriate validator.`

**Comment by danbri** [comment]
This is a compatibility issue between JSON-LD as defined by @w3c and
JSON-LD as implemented by Google. Google’s implementation always was a kind
of profile that was tuned to Schema.org, Web search and Google product
usecases. It should not preclude other uses of the data.   There are some
mismatches between Search proxessing models and the design of JSON-LD -
especially runtime context fetching - which I have raised over the years
with the WG. For sxhema.org use there’s something to be said for avoiding
contexts and using vocab urls instead.

re Google - I no longer work there and have zero visibility into their
deliberations but I am sure they are mindful of the need for compatibility
with other data consumers. The simplest way to do this is by ignoring
rather than showing warnings. It might be that some warnings can be turned
off. @rrlevering is the best contact for this. Cc:ing Alex and Prem by
email as I don’t hsve everyone’s github IDs memorized!

**Comment by rrlevering** [comment]
This issue is done as far as I am concerned.  We changed the error into a readable warning that explains the issue.  It's still a warning because it changes the behavior and can result in unexpected things if you are expecting remote context fetching (which could change all the schema.org typing behavior).

**Comment by ausi** [comment]
> We changed the error into a readable warning that explains the issue.

I cannot confirm that. In my test it still shows up as **“1 ERROR”** in the category of **“Uncategorized Errors”**:
<img width="1660" height="352" alt="Image" src="https://github.com/user-attachments/assets/ec5db773-268d-4c4a-ac21-f73a43648698" />

And the message still does not include any hints that this can be a valid usage as described in https://github.com/schemaorg/schemaorg/issues/2921#issuecomment-2605599575

**Comment by ausi** [comment]
The error message still hasn’t changed.

**Comment by ausi** [comment]
The error message still hasn’t changed.

**Comment by ausi** [comment]
The error message still hasn’t changed.
